# Generated by Django 4.1.5 on 2023-01-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
